pipeline {
    agent any
    stages {
          stage('Pull code from Github') {
        steps {
            git branch: 'main',
                credentialsId: 'my_cred_id',
                url: 'https://github.com/Santhoshkumar-s2305/cloud-formation.git/'
  
        }
    }
       
	stage('Submit Stack') {
            steps {
                withAWS(credentials: 'aws_configure', region: 'us-east-1') {
              sh "aws cloudformation create-stack --stack-name api --template-body file://jenkinslambda/api.json --capabilities CAPABILITY_NAMED_IAM"
                }
            }
        }
    }
}
