pipeline {
    agent any
    stages {
          stage('Pull code from Github') {
        steps {
            git branch: 'main',
                credentialsId: 'my_cred_id',
                url: 'git@test.com/proj/test_proj.git'
  
        }
    }
       
	stage('Submit Stack') {
            steps {
            sh "aws cloudformation create-stack --stack-name s3bucket --template-body file://simplests3cft.json --region 'us-east-1'"
              }
           }
      }
}
